### ISSUE TITLE
Cannot activate logging and monitoring at once

### ISSUE THREAD

**Issue by dixneuf19** [padok-team/terraform-google-gke#19]
I first installed the cluster with this module without activating workload logging or monitoring.

I then wanted to setup it, and added the following two inputs for my module

```hcl
module "kubernetes" {
  source = "github.com/padok-team/terraform-google-gke.git?ref=v3.0.1"
  # ...
  monitoring = true
  logging = true

# ...
```

But it failed with 

```txt
│   with module.this.module.kubernetes.google_container_cluster.this,
│   on .terraform/modules/this.kubernetes/main.tf line 80, in resource "google_container_cluster" "this":
│   80:     enable_components = var.monitoring ? ["SYSTEM_COMPONENTS", "WORKLOADS"] : ["SYSTEM_COMPONENTS"]
```

It seems linked to this issue https://github.com/hashicorp/terraform-provider-google/issues/10361

~~A fix seems to be to set `logging = true` at first, apply and then set `monitoring = true`. It might simply be a GCP limitation (one "operation" at the time)~~

I'm not sure how to fix it, we probably just need to wait for https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1305 and maybe document it for the moment ?

Update:

Monitoring for WORLKLOADS is only available for beta provider, and will be removed on 1.24

> The monitoring_config block supports:
> [enable_components](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#enable_components) - (Optional) The GKE components exposing metrics. SYSTEM_COMPONENTS and in beta provider, both SYSTEM_COMPONENTS and WORKLOADS are supported. (WORKLOADS is deprecated and removed in GKE 1.24.)

**Comment by dixneuf19** [comment]
After like 5 min of research

https://cloud.google.com/stackdriver/docs/solutions/gke/observing

> **Accessing the monitoring dashboard**
> From the Google Cloud console, go to Monitoring:
> [Go to Monitoring](https://console.cloud.google.com/monitoring)
> Select Dashboards and then select one of the following dashboards:
> 
> -     For clusters with Cloud Operations for GKE enabled, select the dashboard named GKE.
> -     For clusters with Legacy Logging and Monitoring enabled, select the dashboard named GKE Clusters.

With only the "SYSTEM" monitoring enabled, I have access on the console to a GCP Managed dashboard "GKE", with all classic k8s metrics I want (CPU, RAM, etc...)

You can then import other dashboards such as https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/master/dashboards/compute/gke-cluster-monitoring.json

To fix this issue, you should remove the "WORKLOADS" option when activate `monitoring = true`, and either keep this variable but when false, making 0 metrics going to GCP, or remove it.

**Comment by Alan-pad** [comment]
Oh it's a new thing

**Comment by Alan-pad** [comment]
PR merged to fix this behavior : https://github.com/padok-team/terraform-google-gke/pull/24
